"use client";
export const runtime = 'edge';

import React from 'react';
import Link from 'next/link';

export default function TermsPage() {
    return (
        <div style={{ minHeight: '100vh', background: 'var(--bg-main)', padding: '4rem 2rem' }}>
            <div className="container" style={{ maxWidth: '800px' }}>
                <Link href="/" style={{ color: 'var(--accent-sepia)', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '2rem', fontWeight: 600 }}>
                    ← Back to Home
                </Link>

                <div className="paper-card" style={{ padding: '4rem', lineHeight: '1.8' }}>
                    <h1 className="handwritten" style={{ fontSize: '3rem', marginBottom: '2rem' }}>Terms of Service</h1>
                    <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem' }}>Last updated: February 21, 2026</p>

                    <section style={{ marginBottom: '2.5rem' }}>
                        <h2 style={{ fontSize: '1.5rem', color: 'var(--text-primary)', marginBottom: '1rem' }}>1. Acceptance of Terms</h2>
                        <p>By accessing and using Junk Journal AI, you agree to be bound by these Terms of Service and all applicable laws and regulations.</p>
                    </section>

                    <section style={{ marginBottom: '2.5rem' }}>
                        <h2 style={{ fontSize: '1.5rem', color: 'var(--text-primary)', marginBottom: '1rem' }}>2. Use License</h2>
                        <p>You are granted a license to use the images generated by Junk Journal AI for both personal and commercial purposes, provided you have a valid subscription/credits.</p>
                    </section>

                    <section style={{ marginBottom: '2.5rem' }}>
                        <h2 style={{ fontSize: '1.5rem', color: 'var(--text-primary)', marginBottom: '1rem' }}>3. Credit System</h2>
                        <p>Credits purchased or earned have a 30-day expiration period from the date of acquisition. Expired credits are non-refundable.</p>
                    </section>

                    <section style={{ marginBottom: '2.5rem' }}>
                        <h2 style={{ fontSize: '1.5rem', color: 'var(--text-primary)', marginBottom: '1rem' }}>4. Restrictions</h2>
                        <p>You may not use the service to generate harmful, illegal, or offensive content. We reserve the right to terminate accounts that violate these terms.</p>
                    </section>

                    <section style={{ marginBottom: '2.5rem' }}>
                        <h2 style={{ fontSize: '1.5rem', color: 'var(--text-primary)', marginBottom: '1rem' }}>5. Disclaimer</h2>
                        <p>The materials on Junk Journal AI are provided on an 'as is' basis. We make no warranties, expressed or implied, regarding the output accuracy or suitability for a specific purpose.</p>
                    </section>
                </div>
            </div>
        </div>
    );
}
